PROGRAM quest1 ;
VAR

SANDU,QUEIJO,PRESUNTO,HAMBURGUER:REAL;

BEGIN
  
  WRITELN('INFORME A QUANTIDADE DE SANDUICHES DESEJADAS:   ');
  READ(SANDU);
  WRITELN();
  QUEIJO:= 100*SANDU/1000;
  PRESUNTO:= 50*SANDU/1000;
  HAMBURGUER:= 100*SANDU/1000;
  WRITELN (QUEIJO, ' KG DE QUEIJO FORAM USADOS! ') ;
  WRITELN (PRESUNTO, ' KG DE PRESUNTO FORAM USADOS! ') ;
  WRITELN (HAMBURGUER, ' KG DE HAMBURGUER FORAM USADOS! ') ;
  
  READKEY;
End.