Program Pzim ;
VAR
VETOR:ARRAY [1..5] OF REAL;
NUM,CONT:INTEGER;
SOMA,MEDIA:REAL;
Begin
  REPEAT
    CONT:=CONT+1;
    WRITELN('ESCREVA UM NÚMERO: ');
    READ(NUM);
    VETOR[CONT]:=NUM;
    SOMA:=SOMA+VETOR[CONT];
		 UNTIL(CONT=5);
    MEDIA:=SOMA/CONT;
    WRITELN('A MEDIA DOS VALORES É: ',MEDIA);
End.