Program PIZZARIA ;
VAR
RESP_PIZZA,RESP:STRING;
PRODUTO:INTEGER;
PIZZA_SABOR,BEBIDA,BEBIDA_REFRIGERANTE,BEBIDA_SUCO:REAL;
Begin
  WRITELN('OLÁ, BEM VINDO A PIZZARIA!');
  REPEAT
    WRITELN('AQUI TEMOS O CARDÁPIO:');
    WRITELN('1------------------PIZZA');
    WRITELN('2------------------BEBIDAS');
    WRITELN('3------------------REPETIR');
    WRITELN('DIGITE O CÓDIGO DO PRODUTO QUE DESEJA: ');
    READ(PRODUTO);
    IF (PRODUTO<1) OR (PRODUTO>3) THEN
    WRITELN('NÃO TEMOS ESSE CÓDIGO DE PRODUTO, TENTE NOVAMENTE');
  UNTIL(PRODUTO=1) OR (PRODUTO=2);
  CLRSCR;
    IF (PRODUTO=1) THEN
    BEGIN
      REPEAT
        WRITELN('OK, VOCÊ DESEJA UMA PIZZA, TEMOS OS SEGUINTES SABORES:');
        WRITELN('1.1--------------PIZZA CALABBRESA');
        WRITELN('1.2--------------PIZZA MUSSARELA');
        WRITELN('1.3--------------PIZZA PORTUGUESA');
        WRITELN('1.4--------------REPETIR AS OPÇÕES');
        WRITELN('1.5--------------VOLTAR AO MENU INICIAL');
        WRITELN('ENTÃO, QUAL SABOR DE PIZZA VOCÊ DESEJA? ');
        READ(PIZZA_SABOR);
        IF (PIZZA_SABOR<1.1) OR (PIZZA_SABOR>1.5) THEN
        WRITELN('CÓDIGO INVÁLIDO, POR FAVOR TENTE NOVAMENTE');
      UNTIL(PIZZA_SABOR=1.1) OR (PIZZA_SABOR=1.2) OR (PIZZA_SABOR=1.3) OR (PIZZA_SABOR=1.5);
    END;
    CLRSCR;
    IF (PIZZA_SABOR=1.1) THEN
    BEGIN
      WRITELN('VOCÊ COMPROU UMA PIZZA CALABRESA');
      WRITELN('DESEJA MAIS ALGUMA COISA? S/SIM N/NÃO: ');
      READ(RESP);
      IF (RESP='S') OR (RESP='s') THEN
      BEGIN
        WRITELN('O QUE DESEJA? 1 - SUCO, 2 - REFRIGERANTE: ');
        READ(RESP_PIZZA);
      END;
    END;
    IF (PIZZA_SABOR=1.2) THEN
    BEGIN
      WRITELN('VOCÊ COMPROU UMA PIZZA MUSSARELA');
      WRITELN('DESEJA MAIS ALGUMA COISA? S/SIM N/NÃO: ');
      READ(RESP);
      IF (RESP='S') OR (RESP='s') THEN
      BEGIN
        WRITELN('O QUE DESEJA? 1 - SUCO, 2 - REFRIGERANTE: ');
        READ(RESP_PIZZA);
      END;
    END;
    IF (PIZZA_SABOR=1.3) THEN
    BEGIN
      WRITELN('VOCÊ COMPROU UMA PIZZA PORTUGUESA');
      WRITELN('DESEJA MAIS ALGUMA COISA? S/SIM N/NÃO: ');
      READ(RESP);
      IF (RESP='S') OR (RESP='s') THEN
      BEGIN
        WRITELN('O QUE DESEJA? 1 - SUCO, 2 - REFRIGERANTE: ');
        READ(RESP_PIZZA);
      END;
    END;
    
    IF (PRODUTO=2) OR (RESP_PIZZA='2') THEN
    BEGIN
      REPEAT
        WRITELN('OK, TEMOS AS SEGUINTES BEBIDAS:');
        WRITELN('2.1------------REFRIGERANTE');
        WRITELN('2.2------------SUCOS');
        WRITELN('2.3------------REPETIR AS OPÇÕES');
        WRITELN('2.4------------VOLTAR AO MENU INICIAL');
        WRITELN('QUAL BEBIDA VOCÊ DESEJA ENTÃO:  ');
        READ(BEBIDA);
        IF (BEBIDA<2.1) OR (BEBIDA>2.4) THEN
        WRITELN('NÃO TEMOS BEBIDA COM ESTE CÓDIGO, POR FAVOR TENTE NOVAMENTE');
      UNTIL(BEBIDA=2.1) OR (BEBIDA=2.2) OR (BEBIDA=2.4);
    END;
    IF (BEBIDA=2.1) THEN
    REPEAT
      WRITELN('OK, TEMOS OS SEGUINTES REFRIGERANTES:');
      WRITELN('2.11---------------GUARANÁ');
      WRITELN('2.12---------------COCA-COLA');
      WRITELN('2.13---------------REPETIR');
      WRITELN('2.14---------------VOLTAR AO MENU INICIAL');
      WRITELN('ENTÃO DIGITE O CÓDIGO DA BEBIDA QUE DESEJA: ');
      READ(BEBIDA_REFRIGERANTE);
      IF (BEBIDA_REFRIGERANTE<2.11) OR (BEBIDA_REFRIGERANTE>2.14) THEN
      WRITELN('CÓDIGO INVÁLIDO, POR FAVOR TENTE NOVAMENTE');
    UNTIL(BEBIDA_REFRIGERANTE=2.11) OR (BEBIDA_REFRIGERANTE=2.12) OR (BEBIDA_REFRIGERANTE=2.14);
    
    IF (BEBIDA_REFRIGERANTE=2.11) OR (BEBIDA_REFRIGERANTE=2.12) THEN
    WRITELN('VOCÊ COMPROU UM REFRIGERANTE');
    
    IF (BEBIDA=2.2) OR (RESP_PIZZA='1') THEN
    BEGIN
      REPEAT
        WRITELN('TEMOS OS SEGUINTES SUCOS:');
        WRITELN('2.21---------------LARANJA');
        WRITELN('2.22---------------MORANGO');
        WRITELN('2.23---------------REPETIR');
        WRITELN('2.24---------------VOLTAR AO MENU INICIAL');
        WRITELN('ENTÃO, QUAL SUCO DESEJA: ');
        READ(BEBIDA_SUCO);
        IF (BEBIDA_SUCO<2.21) OR (BEBIDA_SUCO>2.24) THEN
        WRITELN('CODIGO INVALIDO TENTE NOVAMENTE');
      UNTIL(BEBIDA_SUCO=2.21) OR (BEBIDA_SUCO=2.22) OR (BEBIDA_SUCO>2.24);
    END;
    IF (BEBIDA_SUCO=2.21) OR (BEBIDA_SUCO=2.22) THEN
    WRITELN('OK, VOCÊ COMPROU UM SUCO');
  READKEY;
End.