Program Pzim ;
VAR
TEMP,TEMP2:ARRAY [1..6] OF REAL;
SOMA,MEDIA:REAL;
I,CONT:INTEGER;
Begin
  FOR I:=1 TO 6 DO
  BEGIN
    WRITELN('ESCREVA UMA TEMPERATURA: ');
    READ(TEMP[I]);
    SOMA:=SOMA+TEMP[I];
  END;
  MEDIA:=SOMA/I;
  WRITELN('A MEDIA FOI: ',MEDIA);
  FOR I:=1 TO 6 DO
  BEGIN
    IF (TEMP[I]>MEDIA) THEN
    BEGIN
    CONT:=CONT+1;
    TEMP2[I]:=TEMP[I];
    END;
  END;
  FOR I:=1 TO CONT DO
  BEGIN
    WRITELN('AS TEMPERATURAS ACIMA DA MÉDIA FORAM: ',TEMP2[I]);
  END;
End.