Program	QUEST_1 ;
VAR
I,NUM,SOMA_IMPAR,CONT_PAR:INTEGER;
SOMA_PAR,MEDIA:REAL;
Begin
  REPEAT
    I:=I+1;
    WRITELN('ESCREVA UM NÚMERO ',I,':');
    READ(NUM);
    IF (NUM MOD 2 = 0) AND (NUM<>0)  THEN
    BEGIN
      CONT_PAR:=CONT_PAR+1;
      SOMA_PAR:=SOMA_PAR+NUM
    END
    ELSE
    SOMA_IMPAR:=SOMA_IMPAR+NUM;
  UNTIL(NUM=0);
  MEDIA:=SOMA_PAR/CONT_PAR;
  WRITELN('A MEDIA DOS NÚMEROS PARES É: ',MEDIA);
  WRITELN('A SOMA DOS NÚMEROS IMPARES DIGITADOS É: ',SOMA_IMPAR);
  READKEY;
End.