Program Pzim ;
VAR
NOME:ARRAY [1..10] OF STRING;
NOME_ACHAR:STRING;
J,I:INTEGER;
Begin
  FOR I:=1 TO 10 DO
  BEGIN
    WRITELN('ESCREVA UM NOME: ');
    READ(NOME[I]);
  END;
  WRITELN('ESCREVA UM NOME PARA PESQUISA: ');
  READ(NOME_ACHAR);
  FOR I:=1 TO 10 DO
  BEGIN
    IF (NOME[I]=NOME_ACHAR) THEN
    J:=1;
  END;
  IF (J=1) THEN
  WRITELN('O NOME ESTÁ NA LISTA')
  ELSE
  WRITELN('O NOME NÃO ESTÁ NA LISTA');
End.