Program QUEST_3 ;
VAR
I,ME:INTEGER;
VALOR_ME,CONT,MEDIA,SOMA:REAL;
Begin
  WRITELN('INFORME O NÚMERO TOTAL DE MERCADORIAS NO ESTOQUE: ');
  READ(ME);
  REPEAT
    I:=I+1;
    WRITELN('INFORME O VALOR DE CADA MERCADORIA: ');
    READ(VALOR_ME);
    SOMA:=SOMA+VALOR_ME;
  UNTIL(I=ME);
  MEDIA:=SOMA/ME;
  WRITELN('O VALOR TOTAL DE ESTOQUE É: ',SOMA);
  WRITELN('A MEDIA DOS VALORES E: ',MEDIA);
  READKEY;
End.